apiVersion: v1
kind: ConfigMap
metadata:
  name: n8n-config
  namespace: default
data:
  DB_POSTGRESDB_HOST: "db-n8n-dev.cjg1jd3af1v1.us-east-1.rds.amazonaws.com"
  DB_POSTGRESDB_PORT: "5432"
  DB_POSTGRESDB_DATABASE: "postgres"
  N8N_HOST: "0.0.0.0"
  N8N_SECURE_COOKIE: "false"
