apiVersion: v1
kind: Secret
metadata:
  name: n8n-secrets
  namespace: default
type: Opaque
stringData:
  #db-password: "changeme_db_password"
  db-password: "12345678"  # ← CAMBIAR: Tu contraseña RDS real
  encryption-key: "changeme_encryption_key"  # ← CAMBIAR: Clave segura aleatoria
  db-user: "admin_user"  # ← CAMBIAR: Tu usuario master de RDS
