flowchart TB
    classDef cloud fill:#fff,stroke:#232F3E,stroke-width:2px;
    classDef vpc fill:#fff,stroke:#3B48CC,stroke-width:2px,stroke-dasharray: 5 5;
    classDef pub fill:#e1f8e9,stroke:#2e7d32,stroke-width:1px;
    classDef priv fill:#e3f2fd,stroke:#1565c0,stroke-width:1px;
    classDef db fill:#fff3e0,stroke:#ef6c00,stroke-width:1px;
    classDef k3s fill:#326ce5,color:#fff,stroke-width:2px;

    Cliente([Cliente Web]) -- "HTTPS:443" --> ALB

    subgraph AWS ["AWS Cloud"]
        subgraph VPC ["VPC 172.16.20.0/22"]
            ALB[ALB]
            subgraph PUB1 [Red Pública]
                NAT1[NAT Gateway]
                M1{{Master K3s}}
            end
            subgraph PRIV1 [Red Privada K3s]
                W1[[worker_1]]
                W2[[worker_2]]
                W3[[worker_3]]
                W4[[worker_4]]
            end
            subgraph DB_SUB1 [Red de Datos]
                RDS[(RDS Postgres)]
                EFS[(EFS Storage)]
            end
            IGW[Internet Gateway]
        end
    end

    ALB ====> PUB1
    NAT1 ------> IGW
    M1 -- "Tráfico Interno" --> W1 & W2
    W1 -- "DB: 5432" --> RDS
    W2 -- "DB: 5432" --> RDS
    W1 -- "EFS" --> EFS
    W2 -- "EFS" --> EFS

    class AWS cloud; class VPC vpc;
    class PUB1 pub; class PRIV1 priv; class DB_SUB1 db;
    class M1,W1,W2 k3s;

