# Archivo de ejemplo para personalizar la instalación de Kafka con Helm
# Puedes modificar estos valores según tus necesidades

replicaCount: 1
image:
  registry: registry.bitnami.com
  repository: bitnami/kafka
zookeeper:
  replicaCount: 1
resources:
  requests:
    memory: 512Mi
    cpu: 250m
  limits:
    memory: 1Gi
    cpu: 500m
service:
  type: ClusterIP # Cambia a NodePort o LoadBalancer si lo necesitas
