# Archivo de ejemplo para personalizar la instalación de Kafka con Helm
# Puedes modificar estos valores según tus necesidades

replicaCount: 1
zookeeper:
  replicaCount: 1
resources:
  requests:
    memory: 512Mi
    cpu: 250m
  limits:
    memory: 1Gi
    cpu: 500m
# Para exponer Kafka fuera del clúster, puedes cambiar el tipo de servicio:
service:
  type: ClusterIP # Cambia a NodePort o LoadBalancer si lo necesitas
